const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const html=fs.readFileSync('overwatch-sensitivity.html','utf8');const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(x=>x[1]);const context={window:{},crypto:require('crypto').webcrypto,navigator:{userAgent:'test'},console};vm.createContext(context);vm.runInContext(scripts[0],context);const core=context.window.OWCore;const results=core.selfTests();
function test(name,fn){try{fn();results.push({name,pass:true});}catch(e){results.push({name,pass:false,error:e.message});}}
test('全部四类到期完成，弹丸命中与过期总和守恒',()=>{for(const task of ['A','B','C','D']){const e=new core.Engine(task,core.parameters(),3489);e.advance(48);assert(e.done);assert(Math.abs(e.result().effective-45)<1e-6);if(task==='C')assert.equal(e.stats.shots,e.stats.hits+e.stats.expired);}});
test('D 路线包含对称左右 90/180 与上下，目标不出生在准星内',()=>{const e=new core.Engine('D',core.parameters(),0),ys=[],ps=[];for(let i=0;i<6;i++){ys.push(e.target.yaw-e.camera.yaw);ps.push(e.target.pitch);assert(Math.hypot(...e.relative(e.target))>e.target.radius);e.camera.yaw=e.target.yaw;e.camera.pitch=e.target.pitch;e.complete();}assert.deepEqual(ys,[90,-90,180,-180,0,0]);assert.deepEqual(ps,[0,0,0,0,38,-38]);});
test('已发射弹道不随随后转向改变',()=>{const e=new core.Engine('C',core.parameters(),34);e.advance(.1);const before=JSON.stringify(e.bullets[0]);e.input(100,100,.03);assert.equal(JSON.stringify(e.bullets[0]),before);});
test('相同路线种子重放一致',()=>{const a=new core.Engine('A',core.parameters(),777),b=new core.Engine('A',core.parameters(),777);for(let i=0;i<100;i++){assert.equal(JSON.stringify(a.target),JSON.stringify(b.target));a.complete();b.complete();}});
test('六日期排列中每档各占每个位置两次',()=>{const positions=Array.from({length:3},()=>[0,0,0]);for(let d=0;d<6;d++)core.orderFor(d,3).forEach((v,i)=>positions[v][i]++);assert(positions.flat().every(x=>x===2));});
test('30/60/144Hz 推进下跟枪时间与角误差近似一致',()=>{const run=hz=>{const e=new core.Engine('B',core.parameters(),1);for(let i=1;i<=hz*45;i++)e.advance(i/hz);return e.result();};const a=run(30),b=run(60),c=run(144);assert(Math.abs(a.trackTime-c.trackTime)<.002);assert(Math.abs(a.angularError-c.angularError)<.01);assert(Math.abs(b.trackTime-c.trackTime)<.002);});
test('DPI 未知不产生理论值，物理换算不依赖 DPI',()=>{assert.equal(core.theory(null,5),null);assert.equal(core.cm360({C0:30,S0:5},4),37.5);assert.equal(core.angleScale({B:400,C0:30,S0:5,dpi:800},5),core.angleScale({B:400,C0:30,S0:5,dpi:1600},5));});
test('导入采样拒绝数字字符串、负路径与另一档超范围',()=>{const settings={s0:5},game={measurements:[30,30,30,30],checkS:10,checkC:15};const samples=Array.from({length:8},(_,i)=>({x:i<4?(i%2?4000:-4000):0,y:i>=4?(i%2?4000:-4000):0,path:4000,cm:10,seconds:[0,1,4,5].includes(i)?2:.5,mode:'requested'}));for(const modify of [x=>x[0].x='-4000',x=>x[0].path=-1]){const ss=JSON.parse(JSON.stringify(samples));modify(ss);assert.throws(()=>core.validateCalibration(settings,game,ss,'requested'));}assert.throws(()=>core.validateCalibration(settings,{...game,checkS:1001},samples,'requested'));});
console.log(JSON.stringify(results,null,2));fs.writeFileSync('core-test-results.json',JSON.stringify({testedAt:new Date().toISOString(),results},null,2));process.exitCode=results.some(r=>!r.pass)?1:0;
