const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');const {pathToFileURL}=require('url');const assert=require('assert/strict');
const target=pathToFileURL(require('path').resolve('overwatch-sensitivity.html')).href;
const report=[];
(async()=>{for(const [name,executablePath] of [['Chrome','C:/Program Files/Google/Chrome/Application/chrome.exe'],['Edge','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe']]){
 const browser=await chromium.launch({executablePath,headless:false,args:['--no-first-run','--window-position=0,0','--window-size=1280,900']});
 const context=await browser.newContext({viewport:{width:1280,height:800},acceptDownloads:true,offline:true});const page=await context.newPage();page.setDefaultTimeout(8000);const errors=[];const requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
 const tests=[];async function test(label,fn){try{await fn();tests.push({name:label,pass:true});console.log(name+' PASS '+label);}catch(e){tests.push({name:label,pass:false,error:e.stack});console.log(name+' FAIL '+label+' '+e.message);console.log(await page.evaluate(()=>({sample,run:!!run,locked:!!document.pointerLockElement,message:document.getElementById('lockMessage').textContent})));await page.screenshot({path:'failure-'+name+'.png'});await page.evaluate(()=>closeArena());}}
 await page.goto(target);await page.bringToFront();
 await test('Windows desktop file:// 离线加载，无网络资源',async()=>{assert.equal(new URL(page.url()).protocol,'file:');assert(await page.locator('h1').isVisible());assert.equal(requests.length,0);});
 await page.screenshot({path:`screenshot-${name}-setup.png`,fullPage:true});
 await test('内置核心自检全部通过',async()=>{const results=await page.evaluate(()=>OWCore.selfTests());assert(results.every(x=>x.pass),JSON.stringify(results.filter(x=>!x.pass)));});
 await test('设置表单与未知 DPI',async()=>{await page.locator('#fixedSettings').check();await page.locator('#saveSettings').click();assert(await page.locator('#calibrationCard').isVisible());assert.equal(await page.evaluate(()=>state.settings.dpi),null);});
 await test('校准失败阻止推荐',async()=>{await page.locator('#physicalChecked').check();await page.locator('#finishCalibration').click();assert.match(await page.locator('#message').innerText(),/尚不能推荐/);assert.equal(await page.evaluate(()=>state.calibration),null);});
 await test('真实 Pointer Lock API 请求及 Esc 退出（非物理校准证明）',async()=>{await page.locator('#sampleStart').click();await page.waitForTimeout(2200);await page.locator('#lockButton').click();await page.waitForFunction(()=>document.pointerLockElement!==null&&sample!==null,{},{timeout:5000});await page.keyboard.press('Space');await page.mouse.move(800,450);await page.keyboard.press('Escape');await page.waitForFunction(()=>document.pointerLockElement===null);assert.equal(await page.evaluate(()=>samples.length),0);});
 await test('模拟采样：线性通过、非线性拒绝、第二档校验',async()=>{const res=await page.evaluate(()=>{const s={s0:5,dpi:null,fov:103,aspect:16/9,fovMode:'h16'},g={measurements:[30,30,30,30],checkS:10,checkC:15,segmented:false},samples=Array.from({length:8},(_,i)=>({x:i<4?(i%2?-1:1)*-4000:0,y:i>=4?(i%2?-1:1)*-4000:0,path:4000,cm:10,seconds:[0,1,4,5].includes(i)?2:.5,mode:'requested'}));const c=OWCore.validateCalibration(s,g,samples,'requested');let rejected=false;try{OWCore.validateCalibration(s,g,samples.map((x,i)=>i===0?{...x,x:-6000,path:6000}:x),'requested');}catch{rejected=true;}return{B:c.B,C0:c.C0,rejected};});assert.deepEqual(res,{B:400,C0:30,rejected:true});});
 // Synthetic fixtures remain only in this disposable browser profile. Never saved as real user records.
 await page.evaluate(()=>{samples=Array.from({length:8},(_,i)=>({x:i<4?(i%2?4000:-4000):0,y:i>=4?(i%2?4000:-4000):0,path:4000,cm:10,seconds:[0,1,4,5].includes(i)?2:.5,mode:'requested'}));mode='requested';renderSamples();});
 for(const k of ['c0a','c0b','c0c','c0d'])await page.locator('#'+k).fill('30');await page.locator('#checkS').fill('10');await page.locator('#checkC').fill('15');await page.locator('#physicalChecked').check();await page.locator('#finishCalibration').click();
 await test('候选保存值向导与基线保护',async()=>{assert(await page.locator('#candidateCard').isVisible());await page.locator('#candidate1').fill('5.01');await page.locator('#acceptedValues').check();await page.locator('#freezeCandidates').click();assert.match(await page.locator('#message').innerText(),/必须包含/);await page.locator('#candidate1').fill('5');await page.locator('#freezeCandidates').click();assert(await page.locator('#practicePanel').isVisible());assert.deepEqual(await page.evaluate(()=>state.batch.values),[4,5,6.25]);});
 await test('JSON 完整工作副本导出、验证、导入',async()=>{await page.locator('[data-tab=result]').click();await page.locator('#result > details > summary').click();const downloadP=page.waitForEvent('download');await page.locator('#exportJson').click();const download=await downloadP;const path=await download.path();const data=JSON.parse(fs.readFileSync(path,'utf8'));assert.equal(data.calibration.B,400);assert.equal(data.batch.values.length,3);await page.locator('#importJson').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});assert(await page.locator('#importPreview').isVisible());await page.locator('#confirmImport').click();assert.match(await page.locator('#message').innerText(),/已导入/);});
 await test('非法任务参数及导入内容拒绝',async()=>{const data=await page.evaluate(()=>JSON.parse(JSON.stringify(state)));data.batch.params.dwell=.00001;await page.locator('#importJson').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>document.getElementById('message').textContent.includes('导入被拒绝'));assert.match(await page.locator('#message').innerText(),/导入被拒绝/);assert.equal(await page.evaluate(()=>state.batch.params.dwell),.15);});
 await test('预试不同于正式成绩；参数冻结',async()=>{await page.evaluate(()=>{practiceRuns=[];for(const task of ['A','B','C','D']){const e=new OWCore.Engine(task,state.batch.params,1,12);e.advance(15);const raw=e.result();raw.first=1;raw.stable=1;raw.trackTime=1;raw.hits=1;raw.turns=1;practiceRuns.push({task,raw});}queue=[];next();});await page.locator('[data-tab=test]').click();await page.locator('#freezeDifficulty').click();assert.equal(await page.evaluate(()=>state.batch.frozen),true);assert.equal(await page.evaluate(()=>state.sessions.length),0);});
 await test('正式流程开始、避免重复开始、Esc 中断重测',async()=>{await page.locator('#sameDevice').check();await page.locator('#startSession').click();await page.waitForTimeout(2200);await page.locator('#lockButton').click();await page.waitForFunction(()=>!!run);assert.equal(await page.evaluate(()=>state.sessions.length),1);await page.evaluate(()=>document.getElementById('startSession').click());assert.equal(await page.evaluate(()=>state.sessions.length),1);await page.keyboard.press('Escape');await page.waitForFunction(()=>!run);assert.equal(await page.evaluate(()=>session.adaptations.at(-1).valid),false);assert.equal(await page.evaluate(()=>state.sessions[0].complete),false);assert(await page.locator('#continueRun').isVisible());});
 await test('正式模块中断记录并从头重测',async()=>{await page.evaluate(()=>{current={kind:'formal',task:'A',s:state.batch.values[0],duration:45,seed:123};openArena(current);});await page.waitForTimeout(2200);await page.locator('#lockButton').click();await page.waitForFunction(()=>!!run);await page.waitForTimeout(120);await page.keyboard.press('Escape');await page.waitForFunction(()=>!run);assert.equal(await page.evaluate(()=>session.rounds.at(-1).valid),false);assert.match(await page.evaluate(()=>session.rounds.at(-1).reason),/Esc|鼠标控制视角/);await page.locator('#continueRun').click();await page.waitForTimeout(2200);await page.locator('#lockButton').click();await page.waitForFunction(()=>!!run);assert((await page.evaluate(()=>run.engine.t))<1);await page.keyboard.press('Escape');});
 await test('超过 250ms 停顿及失焦中断',async()=>{await page.locator('#continueRun').click();await page.waitForTimeout(2200);await page.locator('#lockButton').click();await page.waitForFunction(()=>!!run);await page.evaluate(()=>{run.last=performance.now()-300;tick();});assert.match(await page.evaluate(()=>session.rounds.at(-1).reason),/停顿/);await page.locator('#continueRun').click();await page.waitForTimeout(2200);await page.locator('#lockButton').click();await page.waitForFunction(()=>!!run);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.match(await page.evaluate(()=>session.rounds.at(-1).reason),/切到其他窗口/);});
 await test('未完成记录完整 JSON 往返可读',async()=>{const ok=await page.evaluate(()=>{try{OWCore.validateState(JSON.parse(JSON.stringify(state)));return true;}catch(e){return e.message;}});assert.equal(ok,true);});
 await page.locator('#abandonSession').click();
 await test('CSV 下载具有原始字段且中文可读',async()=>{await page.locator('[data-tab=result]').click();const downloadP=page.waitForEvent('download');await page.locator('#exportCsv').click();const download=await downloadP;const content=fs.readFileSync(await download.path(),'utf8');assert(content.includes('calibrationVersion')&&content.includes('exclusionReason')&&content.includes('切到其他窗口'));});
 await test('保存失败明确提醒',async()=>{const r=await page.evaluate(()=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error('test quota');};const ok=save();Storage.prototype.setItem=old;const message=document.getElementById('message').textContent;save();return{ok,message};});assert.equal(r.ok,false);assert.match(r.message,/本地保存失败/);});
 await test('刷新恢复设置和记录，不恢复中断计时',async()=>{await page.reload();assert.equal(await page.evaluate(()=>state.batch.values.length),3);assert.equal(await page.evaluate(()=>run),null);assert.equal(await page.evaluate(()=>state.sessions.length),1);});
 await page.locator('[data-tab=result]').click();await page.screenshot({path:`screenshot-${name}-result.png`,fullPage:true});
 await test('无脚本异常或网络依赖',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);});
 report.push({browser:name,version:browser.version(),headless:false,url:target,offline:true,tests,errors});await browser.close();
 }fs.writeFileSync('browser-test-results.json',JSON.stringify({testedAt:new Date().toISOString(),report},null,2));process.exitCode=report.some(r=>r.tests.some(t=>!t.pass))?1:0;
})().catch(e=>{console.error(e);fs.writeFileSync('browser-test-results.json',JSON.stringify({error:e.stack,report},null,2));process.exitCode=1;});

